services:
  - type: web
    name: SISTEMA-CONTABLE
    runtime: php # <--- Aquí le ordenamos usar PHP nativo
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_SERVICE
        value: laravel